### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by Jish2** [acm-uiuc/resume-book#10]
# Feature #10 - Create Database

**Priority** Highs

## Objective

This story aims to configure the structure of the dynamo table

Consider:

The user needs the fields:

- Name
- Email (can be seperate from illinois email)
- LinkedIn
- ug or grad
- Major
- Minor
- GPA
- Year (expected graduation) in MM/DD
- Bio
- Skills
- Position type (intern, coop, part-time, full time)
- Work Authorization Status
  - Are you authorized to work lawfully in the United States?
  - Will you now or in the future require sponsorship for employment visa status (e.g. H-1B, OPT)?

## Tasks Outline

Routes that should be defined

- GET get user
- POST update user

- POST registrater user
  - require all fields be filled in (non optional fields)

**Comment by LordSunchips** [comment]
Columns of the Database:
UID
Name: String
Email: String
LinkedIn: String (stores the string after the "Linkedin.com/in/..."
UG or Grad: 1-bit binary value (0 for UG, 1 for Grad)
Major: String
Minor: String
GPA: Float (Number)
Grad Month: Number
Grad Year: Number 
Bio: String (character limit???)
Skills: Set of Strings
Position Type: Set of two-bit binary values (00: intern, 01: coop, 10: part-time, 11: full time)
Work Authorization: Binary (0: No, 1: Yes)
Future Sponsorship: Binary (0: No, 1: Yes)
